name: Deploy Afemida via FTP

on:
  push:
    branches:
      - main 

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: FTP Deploy to Server
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.afemidalaw.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  
        remote-dir: /public_html/
